name: Lint

# based on:
#  - https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/master/.github/workflows/lint.yml
#  - https://github.com/NullVoxPopuli/ember-autostash-modifier/blob/master/.github/workflows/ci.yml
#  - https://github.com/emberjs/ember-test-helpers/blob/master/.github/workflows/ci-build.yml
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main

env:
  CI: true

jobs:
  source:
    name: Source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4

      - run: yarn install --frozen-lockfile

      - name: ESLint
        run: yarn lint:js

      - name: Templates
        run: yarn lint:hbs

  tooling:
    name: Tooling
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile
      - name: Semantic Release
        run: yarn semantic-release --dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # docs:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: volta-cli/action@v4

  #   - run: yarn install
  #   - run: yarn lint:docs


  # docs-js-code:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs (JS Code Samples)
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: volta-cli/action@v4

  #   - run: yarn install
  #   - run: yarn lint:docs-js

  commits:
    name: Commit Messages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v4
    - uses: wagoid/commitlint-github-action@v4.1.9
